### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by mattwaggs** [mattwaggs/snake#1]
- [x] ~~add apples for the snake to eat~~
- [x] ~~add scoring~~
- [x] ~~make render method for displaying text on canvas (i.e. 'Game Over')~~
- [ ] better way to start game.
